# Generated by Django 5.2.8 on 2025-11-25 10:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Design Object Type',
                'verbose_name_plural': 'Design Object Types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.CharField(blank=True, default='v1', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('show_stars', models.BooleanField(default=True)),
                ('show_platform', models.BooleanField(default=True)),
                ('show_icon', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Design Template',
                'verbose_name_plural': 'Design Templates',
                'ordering': ['template_type__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template Type',
                'verbose_name_plural': 'Template Types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('shape', 'Shape'), ('palette', 'Color Palette'), ('effect', 'Effect / Shadow'), ('border', 'Border / Radius'), ('fontset', 'Font Set'), ('iconset', 'Icon Set'), ('pattern', 'Pattern / Texture')], max_length=32)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Design Param',
                'verbose_name_plural': 'Design Params',
                'ordering': ['group', 'order_index', 'code'],
                'unique_together': {('group', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='M03_art_studio.objecttype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='M03_art_studio.templatemodel')),
            ],
            options={
                'verbose_name': 'Design Object',
                'verbose_name_plural': 'Design Objects',
                'ordering': ['object_type__code', 'template__code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='template_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design_templates', to='M03_art_studio.templatetypemodel'),
        ),
    ]
