# Generated by Django 5.2.8 on 2025-11-25 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M03_art_studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_objects', to='M03_art_studio.objecttype'),
        ),
        migrations.AlterField(
            model_name='object',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_objects', to='M03_art_studio.templatemodel'),
        ),
    ]
