# Generated by Django 5.2.8 on 2025-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M03_art_studio', '0002_alter_object_object_type_alter_object_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='show_icon',
            field=models.BooleanField(default=False, verbose_name='Merkez ikon görünsün'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='show_platform',
            field=models.BooleanField(default=False, verbose_name='Platform bandı görünsün'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='show_stars',
            field=models.BooleanField(default=False, verbose_name='Yıldızlar görünsün'),
        ),
    ]
