# Generated by Django 5.2.8 on 2025-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M03_art_studio', '0003_alter_templatemodel_show_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodel',
            name='show_effects',
            field=models.BooleanField(default=False, verbose_name='Efektler görünsün'),
        ),
    ]
